version: '3'

services:
  ticker_app:
    container_name: ticker_app
    restart: always
    image: ticker_app
    build: .
    ports:
      - "80:80"
    environment: # Sets environment variable
      - DATABASE_URL=postgresql://postgres:postgres@postgres_db:5432/postgres
      - 'POSTGRES_HOST_AUTH_METHOD:trust'
      - WORKING_DIR=working_dir

    depends_on:
      - postgres_db

  postgres_db:
    container_name: postgres_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - 'POSTGRES_HOST_AUTH_METHOD:trust'
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: {}
